/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import Valuator.Controller;
import Valuator.Frontend;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;

/**
 *
 * @author ondre
 */
public class DCFInput extends javax.swing.JPanel {

    public Frontend frontend;
    public Controller controller;

    /**
     * Creates new form DCFInput
     *
     * @param f
     * @param c
     * @param route
     */
    public DCFInput(Frontend f, Controller c, String route) {
        initComponents();
        controller = c;
        frontend = f;
        setLabels(route);
    }

    /**
     *
     * @param fileRoute
     */
    public void setLabels(String fileRoute) {
        Properties p = new Properties();
        FileInputStream ip;
        try {
            ip = new FileInputStream(fileRoute);
            p.load(ip);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RatioInput.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GrahamOutput.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel45.setText(p.getProperty("jLabel45"));
        jLabel134.setText(p.getProperty("jLabel134"));
        jLabel135.setText(p.getProperty("jLabel135"));
        jLabel136.setText(p.getProperty("jLabel136"));
        jLabel137.setText(p.getProperty("jLabel137"));
        jLabel141.setText(p.getProperty("jLabel141"));
        jLabel142.setText(p.getProperty("jLabel142"));
        jLabel164.setText(p.getProperty("jLabel164"));
        TableColumn t = FCF2.getTableHeader().getColumnModel().getColumn(0);
        t.setHeaderValue(p.getProperty("year"));
        TableColumn ta = FCF2.getTableHeader().getColumnModel().getColumn(1);
        ta.setHeaderValue(p.getProperty("titleCol1"));
        FCF2.getTableHeader().repaint();
        for (int y = 0; y < 9; y++) {
            FCF2.setValueAt(frontend.getActYear() - y, y, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DCFIn = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        FCF2 = new javax.swing.JTable();
        jPanel87 = new javax.swing.JPanel();
        jLabel134 = new javax.swing.JLabel();
        GR3 = new javax.swing.JTextField();
        jLabel135 = new javax.swing.JLabel();
        WACCDCFInn = new javax.swing.JTextField();
        jLabel136 = new javax.swing.JLabel();
        ActFCF2 = new javax.swing.JTextField();
        jLabel137 = new javax.swing.JLabel();
        Debt2 = new javax.swing.JTextField();
        jLabel141 = new javax.swing.JLabel();
        Shares2 = new javax.swing.JTextField();
        jLabel142 = new javax.swing.JLabel();
        CandC2 = new javax.swing.JTextField();
        jLabel164 = new javax.swing.JLabel();
        State2 = new javax.swing.JTextField();

        DCFIn.setForeground(new java.awt.Color(204, 204, 204));
        DCFIn.setPreferredSize(new java.awt.Dimension(850, 600));
        DCFIn.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(0, 153, 255));

        jLabel45.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 51, 51));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Discounted Cash Flow Model Inputs");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        DCFIn.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.GridLayout(1, 2));

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));

        FCF2.setBackground(new java.awt.Color(204, 204, 204));
        FCF2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        FCF2.setForeground(new java.awt.Color(51, 51, 51));
        FCF2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2024", null},
                {"2023", null},
                {"2022", null},
                {"2021", null},
                {"2020", null},
                {"2019", null},
                {"2018", null},
                {"2017", null},
                {"2016", null}
            },
            new String [] {
                "Year", "Free Cash Flow"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FCF2.setRowHeight(40);
        FCF2.setRowMargin(1);
        FCF2.setShowGrid(true);
        FCF2.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(FCF2);

        jPanel14.add(jScrollPane8);

        jPanel87.setBackground(new java.awt.Color(255, 255, 255));
        jPanel87.setLayout(new java.awt.GridLayout(8, 2));

        jLabel134.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel134.setForeground(new java.awt.Color(51, 51, 51));
        jLabel134.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel134.setText("Growth rate (next 5y) [ % ]");
        jPanel87.add(jLabel134);

        GR3.setBackground(new java.awt.Color(204, 204, 204));
        GR3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GR3.setForeground(new java.awt.Color(51, 51, 51));
        GR3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GR3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GR3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GR3KeyTyped(evt);
            }
        });
        jPanel87.add(GR3);

        jLabel135.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel135.setForeground(new java.awt.Color(51, 51, 51));
        jLabel135.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel135.setText("Discount Rate [ % ]");
        jPanel87.add(jLabel135);

        WACCDCFInn.setBackground(new java.awt.Color(204, 204, 204));
        WACCDCFInn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        WACCDCFInn.setForeground(new java.awt.Color(51, 51, 51));
        WACCDCFInn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WACCDCFInn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        WACCDCFInn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                WACCDCFInnKeyTyped(evt);
            }
        });
        jPanel87.add(WACCDCFInn);

        jLabel136.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(51, 51, 51));
        jLabel136.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel136.setText("Actual Free Cash Flow");
        jPanel87.add(jLabel136);

        ActFCF2.setBackground(new java.awt.Color(204, 204, 204));
        ActFCF2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ActFCF2.setForeground(new java.awt.Color(51, 51, 51));
        ActFCF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActFCF2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ActFCF2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ActFCF2KeyTyped(evt);
            }
        });
        jPanel87.add(ActFCF2);

        jLabel137.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel137.setForeground(new java.awt.Color(51, 51, 51));
        jLabel137.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel137.setText("Total Debt");
        jPanel87.add(jLabel137);

        Debt2.setBackground(new java.awt.Color(204, 204, 204));
        Debt2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Debt2.setForeground(new java.awt.Color(51, 51, 51));
        Debt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Debt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Debt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Debt2KeyTyped(evt);
            }
        });
        jPanel87.add(Debt2);

        jLabel141.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel141.setForeground(new java.awt.Color(51, 51, 51));
        jLabel141.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel141.setText("Shares Outstanding");
        jPanel87.add(jLabel141);

        Shares2.setBackground(new java.awt.Color(204, 204, 204));
        Shares2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Shares2.setForeground(new java.awt.Color(51, 51, 51));
        Shares2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Shares2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Shares2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Shares2KeyTyped(evt);
            }
        });
        jPanel87.add(Shares2);

        jLabel142.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel142.setForeground(new java.awt.Color(51, 51, 51));
        jLabel142.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel142.setText("Cash & Cash Equivalents");
        jPanel87.add(jLabel142);

        CandC2.setBackground(new java.awt.Color(204, 204, 204));
        CandC2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CandC2.setForeground(new java.awt.Color(51, 51, 51));
        CandC2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CandC2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CandC2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CandC2KeyTyped(evt);
            }
        });
        jPanel87.add(CandC2);

        jLabel164.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel164.setForeground(new java.awt.Color(51, 51, 51));
        jLabel164.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel164.setText("States Perpentual Growth Rate");
        jPanel87.add(jLabel164);

        State2.setBackground(new java.awt.Color(204, 204, 204));
        State2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        State2.setForeground(new java.awt.Color(51, 51, 51));
        State2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        State2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        State2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                State2KeyTyped(evt);
            }
        });
        jPanel87.add(State2);

        jPanel14.add(jPanel87);

        DCFIn.add(jPanel14, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(DCFIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(DCFIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GR3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GR3KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_GR3KeyTyped

    private void WACCDCFInnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WACCDCFInnKeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_WACCDCFInnKeyTyped

    private void ActFCF2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ActFCF2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_ActFCF2KeyTyped

    private void Debt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Debt2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_Debt2KeyTyped

    private void Shares2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Shares2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_Shares2KeyTyped

    private void CandC2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CandC2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_CandC2KeyTyped

    private void State2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_State2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_State2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActFCF2;
    private javax.swing.JTextField CandC2;
    private javax.swing.JPanel DCFIn;
    private javax.swing.JTextField Debt2;
    private javax.swing.JTable FCF2;
    private javax.swing.JTextField GR3;
    private javax.swing.JTextField Shares2;
    private javax.swing.JTextField State2;
    private javax.swing.JTextField WACCDCFInn;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel87;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    public JTextField getActFCF() {
        return ActFCF2;
    }

    /**
     *
     * @return
     */
    public JTextField getCandC() {
        return CandC2;
    }

    /**
     *
     * @return
     */
    public JTextField getDebt() {
        return Debt2;
    }

    /**
     *
     * @return
     */
    public JTable getFCF() {
        return FCF2;
    }

    /**
     *
     * @return
     */
    public JTextField getGR() {
        return GR3;
    }

    /**
     *
     * @return
     */
    public JTextField getShares() {
        return Shares2;
    }

    /**
     *
     * @return
     */
    public JTextField getState() {
        return State2;
    }

    /**
     *
     * @return
     */
    public JTextField getWACCDCFInn() {
        return WACCDCFInn;
    }

}
