
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import Valuator.ReworkedFrontend;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;

/**
 *
 * @author ondre
 */
public class DCFOutput extends javax.swing.JPanel {

    public ReworkedFrontend frontend;

    /**
     * Creates new form DCFOutput
     */
    public DCFOutput(ReworkedFrontend f, String route) {
        initComponents();
        frontend = f;
        setLabels(route);
    }

    public void setLabels(String fileRoute) {
        Properties p = new Properties();
        FileInputStream ip;
        try {
            ip = new FileInputStream(fileRoute);
            p.load(ip);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RatioInput.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GrahamOutput.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel87.setText(p.getProperty("jLabel87"));
        jLabel98.setText(p.getProperty("jLabel98"));
        jLabel100.setText(p.getProperty("jLabel100"));
        jLabel116.setText(p.getProperty("jLabel116"));
        jLabel117.setText(p.getProperty("jLabel117"));
        jLabel109.setText(p.getProperty("jLabel109"));
        jLabel110.setText(p.getProperty("jLabel110"));
        jLabel111.setText(p.getProperty("jLabel111"));
        jLabel112.setText(p.getProperty("jLabel112"));
        jLabel113.setText(p.getProperty("jLabel113"));
        jLabel114.setText(p.getProperty("jLabel114"));
        jLabel115.setText(p.getProperty("jLabel115"));
        jLabel97.setText(p.getProperty("actprice"));
        jLabel99.setText(p.getProperty("mos"));
        TableColumn td = LastFCF.getTableHeader().getColumnModel().getColumn(0);
        td.setHeaderValue(p.getProperty("year"));
        for (int y = 1; y < 9; y++) {
            TableColumn c = LastFCF.getTableHeader().getColumnModel().getColumn(y);
            c.setHeaderValue(frontend.getActYear() + (y - 8));
        }
        LastFCF.getTableHeader().repaint();
        LastFCF.setValueAt(p.getProperty("tableVal1"), 0, 0);
        LastFCF.setValueAt(p.getProperty("tableVal2"), 1, 0);
        TableColumn te = FutureFCF.getTableHeader().getColumnModel().getColumn(0);
        te.setHeaderValue(p.getProperty("titleCol3"));
        for (int y = 1; y < 14; y++) {
            TableColumn c = FutureFCF.getTableHeader().getColumnModel().getColumn(y);
            c.setHeaderValue(y);
        }
        FutureFCF.getTableHeader().repaint();
        FutureFCF.setValueAt(p.getProperty("year"), 0, 0);
        for (int y = 1; y < 13; y++) {
            FutureFCF.setValueAt(frontend.getActYear() + y, 0, y);
        }
        FutureFCF.setValueAt(p.getProperty("tableVal3"), 0, 13);
        FutureFCF.setValueAt(p.getProperty("tableVal4"), 1, 0);
        FutureFCF.setValueAt(p.getProperty("tableVal5"), 2, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DCFOut = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        ActPriceDCF = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        PriceDCF = new javax.swing.JTextField();
        jLabel99 = new javax.swing.JLabel();
        PillowDCF = new javax.swing.JTextField();
        jLabel100 = new javax.swing.JLabel();
        PriceDCFMoS = new javax.swing.JTextField();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        LastFCF = new javax.swing.JTable();
        jPanel58 = new javax.swing.JPanel();
        jLabel116 = new javax.swing.JLabel();
        GRDCF = new javax.swing.JTextField();
        jLabel117 = new javax.swing.JLabel();
        AvGRDCF = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        FutureFCF = new javax.swing.JTable();
        jPanel57 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        StateDCF = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        WACCDCFOut = new javax.swing.JTextField();
        jLabel111 = new javax.swing.JLabel();
        CashDCF = new javax.swing.JTextField();
        jLabel112 = new javax.swing.JLabel();
        SumFCFDCF = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        DebtDCF = new javax.swing.JTextField();
        jLabel114 = new javax.swing.JLabel();
        EVDCF = new javax.swing.JTextField();
        jLabel115 = new javax.swing.JLabel();
        SharesDCF = new javax.swing.JTextField();

        DCFOut.setLayout(new java.awt.BorderLayout());

        jPanel53.setBackground(new java.awt.Color(0, 153, 255));

        jLabel87.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(51, 51, 51));
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel87.setText("Calculated Discounted Cash Flow Model");

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        DCFOut.add(jPanel53, java.awt.BorderLayout.PAGE_START);

        jPanel54.setBackground(new java.awt.Color(102, 255, 255));
        jPanel54.setLayout(new java.awt.GridLayout(2, 4));

        jLabel97.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(51, 51, 51));
        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel97.setText("Actual stock price:");
        jPanel54.add(jLabel97);

        ActPriceDCF.setEditable(false);
        ActPriceDCF.setBackground(new java.awt.Color(255, 255, 255));
        ActPriceDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ActPriceDCF.setForeground(new java.awt.Color(51, 51, 51));
        ActPriceDCF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActPriceDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel54.add(ActPriceDCF);

        jLabel98.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(51, 51, 51));
        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel98.setText("DCF Price:");
        jPanel54.add(jLabel98);

        PriceDCF.setEditable(false);
        PriceDCF.setBackground(new java.awt.Color(255, 255, 255));
        PriceDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        PriceDCF.setForeground(new java.awt.Color(51, 51, 51));
        PriceDCF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PriceDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel54.add(PriceDCF);

        jLabel99.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(51, 51, 51));
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel99.setText("Margin of Safety:");
        jPanel54.add(jLabel99);

        PillowDCF.setEditable(false);
        PillowDCF.setBackground(new java.awt.Color(255, 255, 255));
        PillowDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        PillowDCF.setForeground(new java.awt.Color(51, 51, 51));
        PillowDCF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PillowDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel54.add(PillowDCF);

        jLabel100.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(51, 51, 51));
        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel100.setText("DCF Price with MoS:");
        jPanel54.add(jLabel100);

        PriceDCFMoS.setEditable(false);
        PriceDCFMoS.setBackground(new java.awt.Color(255, 255, 255));
        PriceDCFMoS.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        PriceDCFMoS.setForeground(new java.awt.Color(51, 51, 51));
        PriceDCFMoS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PriceDCFMoS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel54.add(PriceDCFMoS);

        DCFOut.add(jPanel54, java.awt.BorderLayout.PAGE_END);

        jPanel55.setLayout(new java.awt.GridLayout(2, 1));

        jPanel56.setLayout(new java.awt.GridLayout(3, 1));

        LastFCF.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        LastFCF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Free Cash Flow", null, null, null, null, null, null, null, null},
                {"Growth Rate in %", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Year", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LastFCF.setRowHeight(25);
        LastFCF.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(LastFCF);

        jPanel56.add(jScrollPane5);

        jPanel58.setBackground(new java.awt.Color(255, 255, 255));
        jPanel58.setLayout(new java.awt.GridLayout(1, 4));

        jLabel116.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(51, 51, 51));
        jLabel116.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel116.setText("Growth Rate (next 5 Years)");
        jPanel58.add(jLabel116);

        GRDCF.setEditable(false);
        GRDCF.setBackground(new java.awt.Color(255, 255, 255));
        GRDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GRDCF.setForeground(new java.awt.Color(51, 51, 51));
        GRDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel58.add(GRDCF);

        jLabel117.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(51, 51, 51));
        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel117.setText("Average Growth Rate");
        jPanel58.add(jLabel117);

        AvGRDCF.setEditable(false);
        AvGRDCF.setBackground(new java.awt.Color(255, 255, 255));
        AvGRDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        AvGRDCF.setForeground(new java.awt.Color(51, 51, 51));
        AvGRDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel58.add(AvGRDCF);

        jPanel56.add(jPanel58);

        FutureFCF.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        FutureFCF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Year", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "TV"},
                {"Future FCF", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Discounted FFCF", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PoFFCF", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FutureFCF.setRowHeight(25);
        FutureFCF.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(FutureFCF);

        jPanel56.add(jScrollPane6);

        jPanel55.add(jPanel56);

        jPanel57.setBackground(new java.awt.Color(255, 255, 255));
        jPanel57.setLayout(new java.awt.GridLayout(4, 4));

        jLabel109.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(51, 51, 51));
        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel109.setText("Perpentual Growth Rate");
        jPanel57.add(jLabel109);

        StateDCF.setEditable(false);
        StateDCF.setBackground(new java.awt.Color(255, 255, 255));
        StateDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        StateDCF.setForeground(new java.awt.Color(51, 51, 51));
        StateDCF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StateDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel57.add(StateDCF);

        jLabel110.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(51, 51, 51));
        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel110.setText("Discount Rate");
        jPanel57.add(jLabel110);

        WACCDCFOut.setEditable(false);
        WACCDCFOut.setBackground(new java.awt.Color(255, 255, 255));
        WACCDCFOut.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        WACCDCFOut.setForeground(new java.awt.Color(51, 51, 51));
        WACCDCFOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WACCDCFOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel57.add(WACCDCFOut);

        jLabel111.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(51, 51, 51));
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel111.setText("Cahs & Cash Equivalents");
        jPanel57.add(jLabel111);

        CashDCF.setEditable(false);
        CashDCF.setBackground(new java.awt.Color(255, 255, 255));
        CashDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CashDCF.setForeground(new java.awt.Color(51, 51, 51));
        CashDCF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CashDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel57.add(CashDCF);

        jLabel112.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(51, 51, 51));
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel112.setText("Sum of FCF");
        jPanel57.add(jLabel112);

        SumFCFDCF.setEditable(false);
        SumFCFDCF.setBackground(new java.awt.Color(255, 255, 255));
        SumFCFDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        SumFCFDCF.setForeground(new java.awt.Color(51, 51, 51));
        SumFCFDCF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SumFCFDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel57.add(SumFCFDCF);

        jLabel113.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(51, 51, 51));
        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel113.setText("Total Debt");
        jPanel57.add(jLabel113);

        DebtDCF.setEditable(false);
        DebtDCF.setBackground(new java.awt.Color(255, 255, 255));
        DebtDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        DebtDCF.setForeground(new java.awt.Color(51, 51, 51));
        DebtDCF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DebtDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel57.add(DebtDCF);

        jLabel114.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(51, 51, 51));
        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel114.setText("Equity Value");
        jPanel57.add(jLabel114);

        EVDCF.setEditable(false);
        EVDCF.setBackground(new java.awt.Color(255, 255, 255));
        EVDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EVDCF.setForeground(new java.awt.Color(51, 51, 51));
        EVDCF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EVDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel57.add(EVDCF);

        jLabel115.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(51, 51, 51));
        jLabel115.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel115.setText("Shares Outstanding");
        jPanel57.add(jLabel115);

        SharesDCF.setEditable(false);
        SharesDCF.setBackground(new java.awt.Color(255, 255, 255));
        SharesDCF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        SharesDCF.setForeground(new java.awt.Color(51, 51, 51));
        SharesDCF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SharesDCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel57.add(SharesDCF);

        jPanel55.add(jPanel57);

        DCFOut.add(jPanel55, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(DCFOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(DCFOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActPriceDCF;
    private javax.swing.JTextField AvGRDCF;
    private javax.swing.JTextField CashDCF;
    private javax.swing.JPanel DCFOut;
    private javax.swing.JTextField DebtDCF;
    private javax.swing.JTextField EVDCF;
    private javax.swing.JTable FutureFCF;
    private javax.swing.JTextField GRDCF;
    private javax.swing.JTable LastFCF;
    private javax.swing.JTextField PillowDCF;
    private javax.swing.JTextField PriceDCF;
    private javax.swing.JTextField PriceDCFMoS;
    private javax.swing.JTextField SharesDCF;
    private javax.swing.JTextField StateDCF;
    private javax.swing.JTextField SumFCFDCF;
    private javax.swing.JTextField WACCDCFOut;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables

    public JTextField getActPriceDCF() {
        return ActPriceDCF;
    }

    public JTextField getAvGRDCF() {
        return AvGRDCF;
    }

    public JTextField getCashDCF() {
        return CashDCF;
    }

    public JTextField getDebtDCF() {
        return DebtDCF;
    }

    public JTextField getEVDCF() {
        return EVDCF;
    }

    public JTable getFutureFCF() {
        return FutureFCF;
    }

    public JTextField getGRDCF() {
        return GRDCF;
    }

    public JTable getLastFCF() {
        return LastFCF;
    }

    public JTextField getPillowDCF() {
        return PillowDCF;
    }

    public JTextField getPriceDCF() {
        return PriceDCF;
    }

    public JTextField getPriceDCFMoS() {
        return PriceDCFMoS;
    }

    public JTextField getSharesDCF() {
        return SharesDCF;
    }

    public JTextField getStateDCF() {
        return StateDCF;
    }

    public JTextField getSumFCFDCF() {
        return SumFCFDCF;
    }

    public JTextField getWACCDCFOut() {
        return WACCDCFOut;
    }

}
