/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import Valuator.Frontend;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ondre
 */
public class GrahamOutput extends javax.swing.JPanel {

    private String dirPath;

    /**
     * Creates new form GrahamOutputs
     *
     * @param route
     */
    public GrahamOutput(String route) {
        dirPath = Frontend.getDirPath();
        initComponents();
        setLabels(route);
    }

    /**
     *
     * @param fileRoute
     */
    public void setLabels(String fileRoute) {
        Properties p = new Properties();
        Properties conf = new Properties();
        FileInputStream ip;
        FileInputStream ips;
        try {
            ip = new FileInputStream(fileRoute);
            ips = new FileInputStream(dirPath + "\\config\\config.properties");
            p.load(ip);
            conf.load(ips);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GrahamOutput.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GrahamOutput.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel127.setText(p.getProperty("jLabel127"));
        jLabel156.setText(p.getProperty("jLabel156"));
        jLabel157.setText(p.getProperty("jLabel157"));
        jLabel158.setText(p.getProperty("jLabel158"));
        jLabel139.setText(p.getProperty("jLabel139"));
        jLabel143.setText(p.getProperty("jLabel143"));
        jLabel146.setText(p.getProperty("jLabel146"));
        jLabel147.setText(p.getProperty("jLabel147"));
        jLabel150.setText(p.getProperty("jLabel150"));
        jLabel153.setText(p.getProperty("jLabel153"));
        jLabel154.setText(p.getProperty("jLabel154"));
        jLabel155.setText(p.getProperty("jLabel155"));
        jLabel138.setText(p.getProperty("actprice"));
        jLabel140.setText(p.getProperty("mos"));
        jLabel144.setText(conf.getProperty("PE"));
        jLabel145.setText(conf.getProperty("PERev"));
        jLabel148.setText(conf.getProperty("GRM"));
        jLabel149.setText(conf.getProperty("GRMRev"));
        jLabel151.setText(conf.getProperty("AvgrYeald"));
        jLabel152.setText(conf.getProperty("AvgrYeald"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrahamOut = new javax.swing.JPanel();
        jPanel72 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        jPanel73 = new javax.swing.JPanel();
        jLabel138 = new javax.swing.JLabel();
        ActPriceGraham = new javax.swing.JTextField();
        jLabel140 = new javax.swing.JLabel();
        PillowGraham = new javax.swing.JTextField();
        jPanel74 = new javax.swing.JPanel();
        jPanel75 = new javax.swing.JPanel();
        jLabel156 = new javax.swing.JLabel();
        jPanel76 = new javax.swing.JPanel();
        jLabel157 = new javax.swing.JLabel();
        jPanel77 = new javax.swing.JPanel();
        jLabel158 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        EPSGraham = new javax.swing.JTextField();
        EPSGrahamRev = new javax.swing.JTextField();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        GRGraham = new javax.swing.JTextField();
        GRGrahamRev = new javax.swing.JTextField();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        YGraham = new javax.swing.JTextField();
        YGrahamRev = new javax.swing.JTextField();
        jLabel154 = new javax.swing.JLabel();
        EndGraham = new javax.swing.JTextField();
        EndGrahamRev = new javax.swing.JTextField();
        jLabel155 = new javax.swing.JLabel();
        EndGrahamMoS = new javax.swing.JTextField();
        EndGrahamRevMoS = new javax.swing.JTextField();

        GrahamOut.setForeground(new java.awt.Color(204, 204, 204));
        GrahamOut.setLayout(new java.awt.BorderLayout());

        jPanel72.setBackground(new java.awt.Color(0, 153, 255));

        jLabel127.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(51, 51, 51));
        jLabel127.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel127.setText("Calculated Grahams Formulas");

        javax.swing.GroupLayout jPanel72Layout = new javax.swing.GroupLayout(jPanel72);
        jPanel72.setLayout(jPanel72Layout);
        jPanel72Layout.setHorizontalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel127, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        jPanel72Layout.setVerticalGroup(
            jPanel72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel127, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        GrahamOut.add(jPanel72, java.awt.BorderLayout.PAGE_START);

        jPanel73.setBackground(new java.awt.Color(102, 255, 255));
        jPanel73.setLayout(new java.awt.GridLayout(2, 4));

        jLabel138.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel138.setForeground(new java.awt.Color(51, 51, 51));
        jLabel138.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel138.setText("Actual stock price:");
        jPanel73.add(jLabel138);

        ActPriceGraham.setEditable(false);
        ActPriceGraham.setBackground(new java.awt.Color(255, 255, 255));
        ActPriceGraham.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ActPriceGraham.setForeground(new java.awt.Color(51, 51, 51));
        ActPriceGraham.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActPriceGraham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel73.add(ActPriceGraham);

        jLabel140.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel140.setForeground(new java.awt.Color(51, 51, 51));
        jLabel140.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel140.setText("Margin of Safety:");
        jPanel73.add(jLabel140);

        PillowGraham.setEditable(false);
        PillowGraham.setBackground(new java.awt.Color(255, 255, 255));
        PillowGraham.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        PillowGraham.setForeground(new java.awt.Color(51, 51, 51));
        PillowGraham.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PillowGraham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel73.add(PillowGraham);

        GrahamOut.add(jPanel73, java.awt.BorderLayout.PAGE_END);

        jPanel74.setBackground(new java.awt.Color(255, 255, 255));
        jPanel74.setLayout(new java.awt.GridLayout(9, 3));

        jPanel75.setBackground(new java.awt.Color(102, 255, 255));

        jLabel156.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(51, 51, 51));
        jLabel156.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel156.setText("Partition");

        javax.swing.GroupLayout jPanel75Layout = new javax.swing.GroupLayout(jPanel75);
        jPanel75.setLayout(jPanel75Layout);
        jPanel75Layout.setHorizontalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel156, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        jPanel75Layout.setVerticalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel75Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel156, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel74.add(jPanel75);

        jPanel76.setBackground(new java.awt.Color(102, 255, 255));

        jLabel157.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel157.setForeground(new java.awt.Color(51, 51, 51));
        jLabel157.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel157.setText("Grahams Formula");

        javax.swing.GroupLayout jPanel76Layout = new javax.swing.GroupLayout(jPanel76);
        jPanel76.setLayout(jPanel76Layout);
        jPanel76Layout.setHorizontalGroup(
            jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel157, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        jPanel76Layout.setVerticalGroup(
            jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel157, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel74.add(jPanel76);

        jPanel77.setBackground(new java.awt.Color(102, 255, 255));

        jLabel158.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel158.setForeground(new java.awt.Color(51, 51, 51));
        jLabel158.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel158.setText("Grahams Reversed Formula");

        javax.swing.GroupLayout jPanel77Layout = new javax.swing.GroupLayout(jPanel77);
        jPanel77.setLayout(jPanel77Layout);
        jPanel77Layout.setHorizontalGroup(
            jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel158, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel77Layout.setVerticalGroup(
            jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel158, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel74.add(jPanel77);

        jLabel139.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(51, 51, 51));
        jLabel139.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel139.setText("EPS");
        jPanel74.add(jLabel139);

        EPSGraham.setEditable(false);
        EPSGraham.setBackground(new java.awt.Color(255, 255, 255));
        EPSGraham.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EPSGraham.setForeground(new java.awt.Color(51, 51, 51));
        EPSGraham.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EPSGraham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.add(EPSGraham);

        EPSGrahamRev.setEditable(false);
        EPSGrahamRev.setBackground(new java.awt.Color(255, 255, 255));
        EPSGrahamRev.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EPSGrahamRev.setForeground(new java.awt.Color(51, 51, 51));
        EPSGrahamRev.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EPSGrahamRev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.add(EPSGrahamRev);

        jLabel143.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel143.setForeground(new java.awt.Color(51, 51, 51));
        jLabel143.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel143.setText("P/E ratio");
        jPanel74.add(jLabel143);

        jLabel144.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel144.setForeground(new java.awt.Color(51, 51, 51));
        jLabel144.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel144.setText("8.50");
        jPanel74.add(jLabel144);

        jLabel145.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel145.setForeground(new java.awt.Color(51, 51, 51));
        jLabel145.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel145.setText("7.00");
        jPanel74.add(jLabel145);

        jLabel146.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel146.setForeground(new java.awt.Color(51, 51, 51));
        jLabel146.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel146.setText("Growth rate (next 5 years)");
        jPanel74.add(jLabel146);

        GRGraham.setEditable(false);
        GRGraham.setBackground(new java.awt.Color(255, 255, 255));
        GRGraham.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GRGraham.setForeground(new java.awt.Color(51, 51, 51));
        GRGraham.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GRGraham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.add(GRGraham);

        GRGrahamRev.setEditable(false);
        GRGrahamRev.setBackground(new java.awt.Color(255, 255, 255));
        GRGrahamRev.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GRGrahamRev.setForeground(new java.awt.Color(51, 51, 51));
        GRGrahamRev.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GRGrahamRev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.add(GRGrahamRev);

        jLabel147.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel147.setForeground(new java.awt.Color(51, 51, 51));
        jLabel147.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel147.setText("Multiplier for Growth rate");
        jPanel74.add(jLabel147);

        jLabel148.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel148.setForeground(new java.awt.Color(51, 51, 51));
        jLabel148.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel148.setText("2.00");
        jPanel74.add(jLabel148);

        jLabel149.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel149.setForeground(new java.awt.Color(51, 51, 51));
        jLabel149.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel149.setText("1.00");
        jPanel74.add(jLabel149);

        jLabel150.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel150.setForeground(new java.awt.Color(51, 51, 51));
        jLabel150.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel150.setText("Average yeald");
        jPanel74.add(jLabel150);

        jLabel151.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel151.setForeground(new java.awt.Color(51, 51, 51));
        jLabel151.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel151.setText("4.40");
        jPanel74.add(jLabel151);

        jLabel152.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel152.setForeground(new java.awt.Color(51, 51, 51));
        jLabel152.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel152.setText("4.40");
        jPanel74.add(jLabel152);

        jLabel153.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel153.setForeground(new java.awt.Color(51, 51, 51));
        jLabel153.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel153.setText("AAA Current Yield (Y)");
        jPanel74.add(jLabel153);

        YGraham.setEditable(false);
        YGraham.setBackground(new java.awt.Color(255, 255, 255));
        YGraham.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        YGraham.setForeground(new java.awt.Color(51, 51, 51));
        YGraham.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        YGraham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.add(YGraham);

        YGrahamRev.setEditable(false);
        YGrahamRev.setBackground(new java.awt.Color(255, 255, 255));
        YGrahamRev.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        YGrahamRev.setForeground(new java.awt.Color(51, 51, 51));
        YGrahamRev.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        YGrahamRev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.add(YGrahamRev);

        jLabel154.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel154.setForeground(new java.awt.Color(51, 51, 51));
        jLabel154.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel154.setText("Instrinsic value");
        jPanel74.add(jLabel154);

        EndGraham.setEditable(false);
        EndGraham.setBackground(new java.awt.Color(204, 255, 204));
        EndGraham.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EndGraham.setForeground(new java.awt.Color(204, 204, 204));
        EndGraham.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EndGraham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.add(EndGraham);

        EndGrahamRev.setEditable(false);
        EndGrahamRev.setBackground(new java.awt.Color(204, 255, 204));
        EndGrahamRev.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EndGrahamRev.setForeground(new java.awt.Color(204, 204, 204));
        EndGrahamRev.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EndGrahamRev.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.add(EndGrahamRev);

        jLabel155.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel155.setForeground(new java.awt.Color(51, 51, 51));
        jLabel155.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel155.setText("Instrinsic value with MoS");
        jPanel74.add(jLabel155);

        EndGrahamMoS.setEditable(false);
        EndGrahamMoS.setBackground(new java.awt.Color(255, 255, 204));
        EndGrahamMoS.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EndGrahamMoS.setForeground(new java.awt.Color(204, 204, 204));
        EndGrahamMoS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EndGrahamMoS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.add(EndGrahamMoS);

        EndGrahamRevMoS.setEditable(false);
        EndGrahamRevMoS.setBackground(new java.awt.Color(255, 255, 204));
        EndGrahamRevMoS.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EndGrahamRevMoS.setForeground(new java.awt.Color(204, 204, 204));
        EndGrahamRevMoS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EndGrahamRevMoS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel74.add(EndGrahamRevMoS);

        GrahamOut.add(jPanel74, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(GrahamOut, javax.swing.GroupLayout.PREFERRED_SIZE, 829, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(GrahamOut, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActPriceGraham;
    private javax.swing.JTextField EPSGraham;
    private javax.swing.JTextField EPSGrahamRev;
    private javax.swing.JTextField EndGraham;
    private javax.swing.JTextField EndGrahamMoS;
    private javax.swing.JTextField EndGrahamRev;
    private javax.swing.JTextField EndGrahamRevMoS;
    private javax.swing.JTextField GRGraham;
    private javax.swing.JTextField GRGrahamRev;
    private javax.swing.JPanel GrahamOut;
    private javax.swing.JTextField PillowGraham;
    private javax.swing.JTextField YGraham;
    private javax.swing.JTextField YGrahamRev;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    public JTextField getActPriceGraham() {
        return ActPriceGraham;
    }

    /**
     *
     * @return
     */
    public JTextField getEPSGraham() {
        return EPSGraham;
    }

    /**
     *
     * @return
     */
    public JTextField getEPSGrahamRev() {
        return EPSGrahamRev;
    }

    /**
     *
     * @return
     */
    public JTextField getEndGraham() {
        return EndGraham;
    }

    /**
     *
     * @return
     */
    public JTextField getEndGrahamMoS() {
        return EndGrahamMoS;
    }

    /**
     *
     * @return
     */
    public JTextField getEndGrahamRev() {
        return EndGrahamRev;
    }

    /**
     *
     * @return
     */
    public JTextField getEndGrahamRevMoS() {
        return EndGrahamRevMoS;
    }

    /**
     *
     * @return
     */
    public JTextField getGRGraham() {
        return GRGraham;
    }

    /**
     *
     * @return
     */
    public JTextField getGRGrahamRev() {
        return GRGrahamRev;
    }

    /**
     *
     * @return
     */
    public JPanel getGrahamOut() {
        return GrahamOut;
    }

    /**
     *
     * @return
     */
    public JTextField getPillowGraham() {
        return PillowGraham;
    }

    /**
     *
     * @return
     */
    public JTextField getYGraham() {
        return YGraham;
    }

    /**
     *
     * @return
     */
    public JTextField getYGrahamRev() {
        return YGrahamRev;
    }

}
