/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import Valuator.Controller;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author ondre
 */
public class GrahamInput extends javax.swing.JPanel {

    public Controller controller;

    /**
     * Creates new form GrahamInput
     */
    public GrahamInput(Controller c, String route) {
        initComponents();
        controller = c;
        setLabels(route);
    }

    public void setLabels(String fileRoute) {
        Properties p = new Properties();
        FileInputStream ip;
        try {
            ip = new FileInputStream(fileRoute);
            p.load(ip);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RatioInput.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GrahamOutput.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel59.setText(p.getProperty("jLabel59"));
        jLabel60.setText(p.getProperty("jLabel60"));
        jLabel61.setText(p.getProperty("jLabel61"));
        jLabel62.setText(p.getProperty("jLabel62"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrahamIn = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        EPS = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        GRGrahamInn = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        Y = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();

        GrahamIn.setLayout(new java.awt.BorderLayout());

        jPanel25.setBackground(new java.awt.Color(0, 153, 255));

        jLabel59.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(51, 51, 51));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Grahams and Grahams Reversed Formula Inputs");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        GrahamIn.add(jPanel25, java.awt.BorderLayout.PAGE_START);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setForeground(new java.awt.Color(51, 51, 51));
        jPanel26.setLayout(new java.awt.GridLayout(6, 2));

        jLabel60.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(51, 51, 51));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("EPS (TTM)");
        jPanel26.add(jLabel60);

        EPS.setBackground(new java.awt.Color(204, 204, 204));
        EPS.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EPS.setForeground(new java.awt.Color(51, 51, 51));
        EPS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EPS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EPSKeyTyped(evt);
            }
        });
        jPanel26.add(EPS);

        jLabel61.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(51, 51, 51));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Growth rate (next 5y) [ % ]");
        jPanel26.add(jLabel61);

        GRGrahamInn.setBackground(new java.awt.Color(204, 204, 204));
        GRGrahamInn.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GRGrahamInn.setForeground(new java.awt.Color(51, 51, 51));
        GRGrahamInn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GRGrahamInn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GRGrahamInn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GRGrahamInnKeyTyped(evt);
            }
        });
        jPanel26.add(GRGrahamInn);

        jLabel62.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(51, 51, 51));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("AAA current yield");
        jPanel26.add(jLabel62);

        Y.setBackground(new java.awt.Color(204, 204, 204));
        Y.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Y.setForeground(new java.awt.Color(51, 51, 51));
        Y.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Y.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                YKeyTyped(evt);
            }
        });
        jPanel26.add(Y);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel26.add(jPanel27);

        GrahamIn.add(jPanel26, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(GrahamIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(GrahamIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EPSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EPSKeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_EPSKeyTyped

    private void GRGrahamInnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GRGrahamInnKeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_GRGrahamInnKeyTyped

    private void YKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YKeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_YKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EPS;
    private javax.swing.JTextField GRGrahamInn;
    private javax.swing.JPanel GrahamIn;
    private javax.swing.JTextField Y;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    // End of variables declaration//GEN-END:variables

    public JTextField getEPS() {
        return EPS;
    }

    public JTextField getGRGraham() {
        return GRGrahamInn;
    }

    public JTextField getYInn() {
        return Y;
    }

}
