/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import Valuator.Controller;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author ondre
 */
public class InfoInput extends javax.swing.JPanel {

    public Controller controller;

    /**
     * Creates new form InfoInput
     */
    public InfoInput(Controller c, String route) {
        initComponents();
        controller = c;
        setLabels(route);
    }

    public void setLabels(String fileRoute) {
        Properties p = new Properties();
        FileInputStream ip;
        try {
            ip = new FileInputStream(fileRoute);
            p.load(ip);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RatioInput.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GrahamOutput.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel54.setText(p.getProperty("jLabel54"));
        jLabel55.setText(p.getProperty("jLabel55"));
        jLabel28.setText(p.getProperty("jLabel28"));
        jLabel29.setText(p.getProperty("jLabel29"));
        jLabel30.setText(p.getProperty("jLabel30"));
        jLabel44.setText(p.getProperty("jLabel44"));
        jLabel166.setText(p.getProperty("jLabel166"));
        jLabel31.setText(p.getProperty("jLabel31"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoIn = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        CorpNameField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        CorpStickerField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        StockExchField = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        ActPrice = new javax.swing.JTextField();
        jLabel166 = new javax.swing.JLabel();
        Pillow2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        NotesField = new javax.swing.JTextField();

        InfoIn.setBackground(new java.awt.Color(255, 255, 255));
        InfoIn.setMinimumSize(new java.awt.Dimension(620, 600));
        InfoIn.setPreferredSize(new java.awt.Dimension(620, 600));
        InfoIn.setLayout(new java.awt.GridLayout(7, 2));

        jPanel18.setBackground(new java.awt.Color(0, 153, 255));

        jLabel54.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 51, 51));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Stock");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        InfoIn.add(jPanel18);

        jPanel16.setBackground(new java.awt.Color(0, 153, 255));

        jLabel55.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(51, 51, 51));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Information");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        InfoIn.add(jPanel16);

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Corporation:");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel28.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        InfoIn.add(jLabel28);

        CorpNameField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CorpNameField.setForeground(new java.awt.Color(204, 204, 204));
        CorpNameField.setBorder(null);
        CorpNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CorpNameFieldKeyTyped(evt);
            }
        });
        InfoIn.add(CorpNameField);

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Corporation sticker:");
        InfoIn.add(jLabel29);

        CorpStickerField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CorpStickerField.setForeground(new java.awt.Color(204, 204, 204));
        CorpStickerField.setBorder(null);
        CorpStickerField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CorpStickerFieldKeyTyped(evt);
            }
        });
        InfoIn.add(CorpStickerField);

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Stock exchange:");
        InfoIn.add(jLabel30);

        StockExchField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        StockExchField.setForeground(new java.awt.Color(204, 204, 204));
        StockExchField.setBorder(null);
        StockExchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StockExchFieldKeyTyped(evt);
            }
        });
        InfoIn.add(StockExchField);

        jLabel44.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 51, 51));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Actual Price:");
        InfoIn.add(jLabel44);

        ActPrice.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ActPrice.setForeground(new java.awt.Color(204, 204, 204));
        ActPrice.setBorder(null);
        ActPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ActPriceKeyTyped(evt);
            }
        });
        InfoIn.add(ActPrice);

        jLabel166.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel166.setForeground(new java.awt.Color(51, 51, 51));
        jLabel166.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel166.setText("Margin of Safety [ % ]");
        InfoIn.add(jLabel166);

        Pillow2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Pillow2.setForeground(new java.awt.Color(204, 204, 204));
        Pillow2.setBorder(null);
        Pillow2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Pillow2KeyTyped(evt);
            }
        });
        InfoIn.add(Pillow2);

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Notes:");
        InfoIn.add(jLabel31);

        NotesField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NotesField.setForeground(new java.awt.Color(204, 204, 204));
        NotesField.setBorder(null);
        NotesField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NotesFieldKeyTyped(evt);
            }
        });
        InfoIn.add(NotesField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(InfoIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(InfoIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CorpNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorpNameFieldKeyTyped
        controller.letterCheck(evt);
    }//GEN-LAST:event_CorpNameFieldKeyTyped

    private void CorpStickerFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorpStickerFieldKeyTyped
        controller.letterCheck(evt);
    }//GEN-LAST:event_CorpStickerFieldKeyTyped

    private void StockExchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StockExchFieldKeyTyped
        controller.letterCheck(evt);
    }//GEN-LAST:event_StockExchFieldKeyTyped

    private void ActPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ActPriceKeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_ActPriceKeyTyped

    private void Pillow2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pillow2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_Pillow2KeyTyped

    private void NotesFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NotesFieldKeyTyped
        controller.letterCheck(evt);
    }//GEN-LAST:event_NotesFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActPrice;
    private javax.swing.JTextField CorpNameField;
    private javax.swing.JTextField CorpStickerField;
    private javax.swing.JPanel InfoIn;
    private javax.swing.JTextField NotesField;
    private javax.swing.JTextField Pillow2;
    private javax.swing.JTextField StockExchField;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    // End of variables declaration//GEN-END:variables

    public JTextField getActPrice() {
        return ActPrice;
    }

    public JTextField getCorpName() {
        return CorpNameField;
    }

    public JTextField getSticker() {
        return CorpStickerField;
    }

    public JTextField getNotes() {
        return NotesField;
    }

    public JTextField getPillow() {
        return Pillow2;
    }

    public JTextField getStockExchange() {
        return StockExchField;
    }

}
