/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import Valuator.Controller;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author ondre
 */
public class NAVInput extends javax.swing.JPanel {

    public Controller controller;

    /**
     * Creates new form NAVInput
     */
    public NAVInput(Controller c, String route) {
        initComponents();
        controller = c;
        setLabels(route);
    }

    public void setLabels(String fileRoute) {
        Properties p = new Properties();
        FileInputStream ip;
        try {
            ip = new FileInputStream(fileRoute);
            p.load(ip);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RatioInput.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GrahamOutput.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel63.setText(p.getProperty("jLabel63"));
        jLabel64.setText(p.getProperty("jLabel64"));
        jLabel65.setText(p.getProperty("jLabel65"));
        jLabel66.setText(p.getProperty("jLabel66"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NAVIn = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        TotalAssets = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        TotalLiab = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        SharesOut = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();

        NAVIn.setForeground(new java.awt.Color(204, 204, 204));
        NAVIn.setToolTipText("");
        NAVIn.setLayout(new java.awt.BorderLayout());

        jPanel28.setBackground(new java.awt.Color(0, 153, 255));

        jLabel63.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(51, 51, 51));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Net Asset Value Inputs");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        NAVIn.add(jPanel28, java.awt.BorderLayout.PAGE_START);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setLayout(new java.awt.GridLayout(6, 2));

        jLabel64.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(51, 51, 51));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Total Assets");
        jPanel29.add(jLabel64);

        TotalAssets.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TotalAssets.setForeground(new java.awt.Color(204, 204, 204));
        TotalAssets.setToolTipText("");
        TotalAssets.setBorder(null);
        TotalAssets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TotalAssetsKeyTyped(evt);
            }
        });
        jPanel29.add(TotalAssets);

        jLabel65.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(51, 51, 51));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Total Liabilities");
        jPanel29.add(jLabel65);

        TotalLiab.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TotalLiab.setForeground(new java.awt.Color(204, 204, 204));
        TotalLiab.setToolTipText("");
        TotalLiab.setBorder(null);
        TotalLiab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TotalLiabKeyTyped(evt);
            }
        });
        jPanel29.add(TotalLiab);

        jLabel66.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(51, 51, 51));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Total number of outstanding share");
        jPanel29.add(jLabel66);

        SharesOut.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        SharesOut.setForeground(new java.awt.Color(204, 204, 204));
        SharesOut.setToolTipText("");
        SharesOut.setBorder(null);
        SharesOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SharesOutKeyTyped(evt);
            }
        });
        jPanel29.add(SharesOut);

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel30);

        NAVIn.add(jPanel29, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(NAVIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(NAVIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TotalAssetsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalAssetsKeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_TotalAssetsKeyTyped

    private void TotalLiabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalLiabKeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_TotalLiabKeyTyped

    private void SharesOutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SharesOutKeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_SharesOutKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NAVIn;
    private javax.swing.JTextField SharesOut;
    private javax.swing.JTextField TotalAssets;
    private javax.swing.JTextField TotalLiab;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    // End of variables declaration//GEN-END:variables

    public JTextField getSharesOut() {
        return SharesOut;
    }

    public JTextField getTotalAssets() {
        return TotalAssets;
    }

    public JTextField getTotalLiab() {
        return TotalLiab;
    }

}
