/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author ondre
 */
public class RatioOutput extends javax.swing.JPanel {

    /**
     * Creates new form RatioOutput
     */
    public RatioOutput(String route) {
        initComponents();
        setLabels(route);
    }

    public void setLabels(String fileRoute) {
        Properties p = new Properties();
        FileInputStream ip;
        try {
            ip = new FileInputStream(fileRoute);
            p.load(ip);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RatioInput.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GrahamOutput.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel86.setText(p.getProperty("jLabel86"));
        jLabel89.setText(p.getProperty("jLabel89"));
        jLabel90.setText(p.getProperty("jLabel90"));
        jLabel91.setText(p.getProperty("jLabel91"));
        jLabel92.setText(p.getProperty("jLabel92"));
        jLabel93.setText(p.getProperty("jLabel93"));
        jLabel94.setText(p.getProperty("jLabel94"));
        jLabel95.setText(p.getProperty("jLabel95"));
        jLabel96.setText(p.getProperty("jLabel96"));
        jLabel101.setText(p.getProperty("jLabel101"));
        jLabel102.setText(p.getProperty("jLabel102"));
        jLabel103.setText(p.getProperty("jLabel103"));
        jLabel104.setText(p.getProperty("jLabel104"));
        jLabel105.setText(p.getProperty("jLabel105"));
        jLabel106.setText(p.getProperty("jLabel106"));
        jLabel107.setText(p.getProperty("jLabel107"));
        jLabel108.setText(p.getProperty("jLabel108"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RatioOut = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        GM = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        OM = new javax.swing.JTextField();
        jLabel91 = new javax.swing.JLabel();
        EPSRatio = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        PpE = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        CLiq = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        PpB = new javax.swing.JTextField();
        jLabel95 = new javax.swing.JLabel();
        DpE = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        PayOut = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        ROA = new javax.swing.JTextField();
        jLabel102 = new javax.swing.JLabel();
        ROE = new javax.swing.JTextField();
        jLabel103 = new javax.swing.JLabel();
        ROS = new javax.swing.JTextField();
        jLabel104 = new javax.swing.JLabel();
        RN = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        Indebtedness = new javax.swing.JTextField();
        jLabel106 = new javax.swing.JLabel();
        ReceivablesTime = new javax.swing.JTextField();
        jLabel107 = new javax.swing.JLabel();
        LiabilitiesTime = new javax.swing.JTextField();
        jLabel108 = new javax.swing.JLabel();
        InventoryTime = new javax.swing.JTextField();

        RatioOut.setPreferredSize(new java.awt.Dimension(900, 600));
        RatioOut.setLayout(new java.awt.BorderLayout());

        jPanel51.setBackground(new java.awt.Color(0, 153, 255));

        jLabel86.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(51, 51, 51));
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("Summary ratio answers");

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel86, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel86, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        RatioOut.add(jPanel51, java.awt.BorderLayout.PAGE_START);

        jPanel52.setBackground(new java.awt.Color(255, 255, 255));
        jPanel52.setLayout(new java.awt.GridLayout(8, 4));

        jLabel89.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(51, 51, 51));
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel89.setText("Gross Margin");
        jPanel52.add(jLabel89);

        GM.setEditable(false);
        GM.setBackground(new java.awt.Color(255, 255, 255));
        GM.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GM.setForeground(new java.awt.Color(51, 51, 51));
        GM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(GM);

        jLabel90.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(51, 51, 51));
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("Operating Margin");
        jPanel52.add(jLabel90);

        OM.setEditable(false);
        OM.setBackground(new java.awt.Color(255, 255, 255));
        OM.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        OM.setForeground(new java.awt.Color(51, 51, 51));
        OM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        OM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(OM);

        jLabel91.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(51, 51, 51));
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel91.setText("Earinings per Share (EPS)");
        jPanel52.add(jLabel91);

        EPSRatio.setEditable(false);
        EPSRatio.setBackground(new java.awt.Color(255, 255, 255));
        EPSRatio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EPSRatio.setForeground(new java.awt.Color(51, 51, 51));
        EPSRatio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EPSRatio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(EPSRatio);

        jLabel92.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(51, 51, 51));
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel92.setText("Price / Earinings");
        jPanel52.add(jLabel92);

        PpE.setEditable(false);
        PpE.setBackground(new java.awt.Color(255, 255, 255));
        PpE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        PpE.setForeground(new java.awt.Color(51, 51, 51));
        PpE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PpE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(PpE);

        jLabel93.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(51, 51, 51));
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel93.setText("Current liquidity");
        jPanel52.add(jLabel93);

        CLiq.setEditable(false);
        CLiq.setBackground(new java.awt.Color(255, 255, 255));
        CLiq.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CLiq.setForeground(new java.awt.Color(51, 51, 51));
        CLiq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CLiq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(CLiq);

        jLabel94.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(51, 51, 51));
        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel94.setText("Price / Book");
        jPanel52.add(jLabel94);

        PpB.setEditable(false);
        PpB.setBackground(new java.awt.Color(255, 255, 255));
        PpB.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        PpB.setForeground(new java.awt.Color(51, 51, 51));
        PpB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PpB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(PpB);

        jLabel95.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(51, 51, 51));
        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel95.setText("Debt / Equity");
        jPanel52.add(jLabel95);

        DpE.setEditable(false);
        DpE.setBackground(new java.awt.Color(255, 255, 255));
        DpE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        DpE.setForeground(new java.awt.Color(51, 51, 51));
        DpE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DpE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(DpE);

        jLabel96.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(51, 51, 51));
        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel96.setText("Payout Ratio");
        jPanel52.add(jLabel96);

        PayOut.setEditable(false);
        PayOut.setBackground(new java.awt.Color(255, 255, 255));
        PayOut.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        PayOut.setForeground(new java.awt.Color(51, 51, 51));
        PayOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PayOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(PayOut);

        jLabel101.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(51, 51, 51));
        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel101.setText("Return on Assets (ROA)");
        jPanel52.add(jLabel101);

        ROA.setEditable(false);
        ROA.setBackground(new java.awt.Color(255, 255, 255));
        ROA.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ROA.setForeground(new java.awt.Color(51, 51, 51));
        ROA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ROA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(ROA);

        jLabel102.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(51, 51, 51));
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setText("Return on Equity (ROE)");
        jPanel52.add(jLabel102);

        ROE.setEditable(false);
        ROE.setBackground(new java.awt.Color(255, 255, 255));
        ROE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ROE.setForeground(new java.awt.Color(51, 51, 51));
        ROE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ROE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(ROE);

        jLabel103.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(51, 51, 51));
        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel103.setText("Return on Sales (ROS)");
        jPanel52.add(jLabel103);

        ROS.setEditable(false);
        ROS.setBackground(new java.awt.Color(255, 255, 255));
        ROS.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ROS.setForeground(new java.awt.Color(51, 51, 51));
        ROS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ROS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(ROS);

        jLabel104.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(51, 51, 51));
        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel104.setText("Cost-effectiveness");
        jPanel52.add(jLabel104);

        RN.setEditable(false);
        RN.setBackground(new java.awt.Color(255, 255, 255));
        RN.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        RN.setForeground(new java.awt.Color(51, 51, 51));
        RN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(RN);

        jLabel105.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(51, 51, 51));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("Total indebtedness of the enterprise");
        jPanel52.add(jLabel105);

        Indebtedness.setEditable(false);
        Indebtedness.setBackground(new java.awt.Color(255, 255, 255));
        Indebtedness.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Indebtedness.setForeground(new java.awt.Color(51, 51, 51));
        Indebtedness.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Indebtedness.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(Indebtedness);

        jLabel106.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(51, 51, 51));
        jLabel106.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel106.setText("Period of turnover of receivables");
        jPanel52.add(jLabel106);

        ReceivablesTime.setEditable(false);
        ReceivablesTime.setBackground(new java.awt.Color(255, 255, 255));
        ReceivablesTime.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ReceivablesTime.setForeground(new java.awt.Color(51, 51, 51));
        ReceivablesTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ReceivablesTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(ReceivablesTime);

        jLabel107.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(51, 51, 51));
        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel107.setText("Period of turnover of liabilities");
        jPanel52.add(jLabel107);

        LiabilitiesTime.setEditable(false);
        LiabilitiesTime.setBackground(new java.awt.Color(255, 255, 255));
        LiabilitiesTime.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        LiabilitiesTime.setForeground(new java.awt.Color(51, 51, 51));
        LiabilitiesTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LiabilitiesTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(LiabilitiesTime);

        jLabel108.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(51, 51, 51));
        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel108.setText("Inventory turnover time");
        jPanel52.add(jLabel108);

        InventoryTime.setEditable(false);
        InventoryTime.setBackground(new java.awt.Color(255, 255, 255));
        InventoryTime.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        InventoryTime.setForeground(new java.awt.Color(51, 51, 51));
        InventoryTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InventoryTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel52.add(InventoryTime);

        RatioOut.add(jPanel52, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(RatioOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(RatioOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CLiq;
    private javax.swing.JTextField DpE;
    private javax.swing.JTextField EPSRatio;
    private javax.swing.JTextField GM;
    private javax.swing.JTextField Indebtedness;
    private javax.swing.JTextField InventoryTime;
    private javax.swing.JTextField LiabilitiesTime;
    private javax.swing.JTextField OM;
    private javax.swing.JTextField PayOut;
    private javax.swing.JTextField PpB;
    private javax.swing.JTextField PpE;
    private javax.swing.JTextField RN;
    private javax.swing.JTextField ROA;
    private javax.swing.JTextField ROE;
    private javax.swing.JTextField ROS;
    private javax.swing.JPanel RatioOut;
    private javax.swing.JTextField ReceivablesTime;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    // End of variables declaration//GEN-END:variables

    public JTextField getCLiq() {
        return CLiq;
    }

    public JTextField getDpE() {
        return DpE;
    }

    public JTextField getEPSRatio() {
        return EPSRatio;
    }

    public JTextField getGM() {
        return GM;
    }

    public JTextField getIndebtedness() {
        return Indebtedness;
    }

    public JTextField getInventoryTime() {
        return InventoryTime;
    }

    public JTextField getLiabilitiesTime() {
        return LiabilitiesTime;
    }

    public JTextField getOM() {
        return OM;
    }

    public JTextField getPayOut() {
        return PayOut;
    }

    public JTextField getPpB() {
        return PpB;
    }

    public JTextField getPpE() {
        return PpE;
    }

    public JTextField getRN() {
        return RN;
    }

    public JTextField getROA() {
        return ROA;
    }

    public JTextField getROE() {
        return ROE;
    }

    public JTextField getROS() {
        return ROS;
    }

    public JTextField getReceivablesTime() {
        return ReceivablesTime;
    }

}
