/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import Valuator.Controller;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ondre
 */
public class RatioInput extends javax.swing.JPanel {

    public Controller controller;

    /**
     * Creates new form RatioInputs
     */
    public RatioInput(Controller c, String route) {
        initComponents();
        controller = c;
        setLabels(route);
    }

    public void setLabels(String fileRoute) {
        Properties p = new Properties();
        FileInputStream ip;
        try {
            ip = new FileInputStream(fileRoute);
            p.load(ip);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RatioInput.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GrahamOutput.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel191.setText(p.getProperty("jLabel191"));
        jLabel192.setText(p.getProperty("jLabel192"));
        jLabel194.setText(p.getProperty("jLabel194"));
        jLabel195.setText(p.getProperty("jLabel195"));
        jLabel196.setText(p.getProperty("jLabel196"));
        jLabel197.setText(p.getProperty("jLabel197"));
        jLabel198.setText(p.getProperty("jLabel198"));
        jLabel199.setText(p.getProperty("jLabel199"));
        jLabel200.setText(p.getProperty("jLabel200"));
        jLabel201.setText(p.getProperty("jLabel201"));
        jLabel202.setText(p.getProperty("jLabel202"));
        jLabel203.setText(p.getProperty("jLabel203"));
        jLabel204.setText(p.getProperty("jLabel204"));
        jLabel205.setText(p.getProperty("jLabel205"));
        jLabel206.setText(p.getProperty("jLabel206"));
        jLabel207.setText(p.getProperty("jLabel207"));
        jLabel208.setText(p.getProperty("jLabel208"));
        jLabel209.setText(p.getProperty("jLabel209"));
        jLabel210.setText(p.getProperty("jLabel210"));
        jLabel211.setText(p.getProperty("jLabel211"));
        jLabel212.setText(p.getProperty("jLabel212"));
        jLabel213.setText(p.getProperty("jLabel213"));
        jLabel214.setText(p.getProperty("jLabel214"));
        jLabel215.setText(p.getProperty("jLabel215"));
        jLabel216.setText(p.getProperty("jLabel216"));
        jLabel217.setText(p.getProperty("jLabel217"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RatioIn = new javax.swing.JPanel();
        jPanel92 = new javax.swing.JPanel();
        jLabel191 = new javax.swing.JLabel();
        jLabel192 = new javax.swing.JLabel();
        jPanel93 = new javax.swing.JPanel();
        jPanel94 = new javax.swing.JPanel();
        jLabel194 = new javax.swing.JLabel();
        TRevenue2 = new javax.swing.JTextField();
        jLabel195 = new javax.swing.JLabel();
        CofRevenue2 = new javax.swing.JTextField();
        jLabel196 = new javax.swing.JLabel();
        OpExpense2 = new javax.swing.JTextField();
        jLabel197 = new javax.swing.JLabel();
        OthIncome2 = new javax.swing.JTextField();
        jLabel198 = new javax.swing.JLabel();
        NIncome2 = new javax.swing.JTextField();
        jLabel199 = new javax.swing.JLabel();
        EBIT2 = new javax.swing.JTextField();
        jPanel95 = new javax.swing.JPanel();
        jLabel200 = new javax.swing.JLabel();
        jPanel96 = new javax.swing.JPanel();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        ComDiv2 = new javax.swing.JTextField();
        jPanel97 = new javax.swing.JPanel();
        jLabel203 = new javax.swing.JLabel();
        jPanel98 = new javax.swing.JPanel();
        jLabel204 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        Taxes2 = new javax.swing.JTextField();
        jLabel206 = new javax.swing.JLabel();
        IntExp2 = new javax.swing.JTextField();
        jPanel99 = new javax.swing.JPanel();
        jLabel207 = new javax.swing.JLabel();
        TAssets2 = new javax.swing.JTextField();
        jLabel208 = new javax.swing.JLabel();
        CurAssets2 = new javax.swing.JTextField();
        jLabel209 = new javax.swing.JLabel();
        Receivable2 = new javax.swing.JTextField();
        jLabel210 = new javax.swing.JLabel();
        Inv2 = new javax.swing.JTextField();
        jLabel211 = new javax.swing.JLabel();
        TLiabilities2 = new javax.swing.JTextField();
        jLabel212 = new javax.swing.JLabel();
        CurLiabilities2 = new javax.swing.JTextField();
        jLabel213 = new javax.swing.JLabel();
        TEGMI2 = new javax.swing.JTextField();
        jLabel214 = new javax.swing.JLabel();
        SHEquity2 = new javax.swing.JTextField();
        jLabel215 = new javax.swing.JLabel();
        CapLO2 = new javax.swing.JTextField();
        jLabel216 = new javax.swing.JLabel();
        TanBookVal2 = new javax.swing.JTextField();
        jLabel217 = new javax.swing.JLabel();
        OrShNum2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(51, 51, 51));

        RatioIn.setBackground(new java.awt.Color(255, 255, 255));
        RatioIn.setForeground(new java.awt.Color(204, 204, 204));
        RatioIn.setLayout(new java.awt.BorderLayout());

        jPanel92.setBackground(new java.awt.Color(0, 153, 255));
        jPanel92.setLayout(new java.awt.GridLayout(1, 2));

        jLabel191.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel191.setForeground(new java.awt.Color(51, 51, 51));
        jLabel191.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel191.setText("Income Statement");
        jPanel92.add(jLabel191);

        jLabel192.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel192.setForeground(new java.awt.Color(51, 51, 51));
        jLabel192.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel192.setText("Balance Sheet");
        jPanel92.add(jLabel192);

        RatioIn.add(jPanel92, java.awt.BorderLayout.PAGE_START);

        jPanel93.setBackground(new java.awt.Color(255, 255, 255));
        jPanel93.setLayout(new java.awt.GridLayout(1, 2));

        jPanel94.setBackground(new java.awt.Color(255, 255, 255));
        jPanel94.setForeground(new java.awt.Color(51, 51, 51));
        jPanel94.setLayout(new java.awt.GridLayout(12, 2));

        jLabel194.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel194.setForeground(new java.awt.Color(51, 51, 51));
        jLabel194.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel194.setText("Total Revenue");
        jPanel94.add(jLabel194);

        TRevenue2.setBackground(new java.awt.Color(204, 204, 204));
        TRevenue2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TRevenue2.setForeground(new java.awt.Color(51, 51, 51));
        TRevenue2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TRevenue2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TRevenue2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TRevenue2KeyTyped(evt);
            }
        });
        jPanel94.add(TRevenue2);

        jLabel195.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel195.setForeground(new java.awt.Color(51, 51, 51));
        jLabel195.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel195.setText("Cost of Revenue");
        jPanel94.add(jLabel195);

        CofRevenue2.setBackground(new java.awt.Color(204, 204, 204));
        CofRevenue2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CofRevenue2.setForeground(new java.awt.Color(51, 51, 51));
        CofRevenue2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CofRevenue2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CofRevenue2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CofRevenue2KeyTyped(evt);
            }
        });
        jPanel94.add(CofRevenue2);

        jLabel196.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel196.setForeground(new java.awt.Color(51, 51, 51));
        jLabel196.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel196.setText("Operating expense ");
        jPanel94.add(jLabel196);

        OpExpense2.setBackground(new java.awt.Color(204, 204, 204));
        OpExpense2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        OpExpense2.setForeground(new java.awt.Color(51, 51, 51));
        OpExpense2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        OpExpense2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        OpExpense2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OpExpense2KeyTyped(evt);
            }
        });
        jPanel94.add(OpExpense2);

        jLabel197.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel197.setForeground(new java.awt.Color(51, 51, 51));
        jLabel197.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel197.setText("Other Income Expense");
        jPanel94.add(jLabel197);

        OthIncome2.setBackground(new java.awt.Color(204, 204, 204));
        OthIncome2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        OthIncome2.setForeground(new java.awt.Color(51, 51, 51));
        OthIncome2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        OthIncome2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        OthIncome2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OthIncome2KeyTyped(evt);
            }
        });
        jPanel94.add(OthIncome2);

        jLabel198.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel198.setForeground(new java.awt.Color(51, 51, 51));
        jLabel198.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel198.setText("Net Income");
        jPanel94.add(jLabel198);

        NIncome2.setBackground(new java.awt.Color(204, 204, 204));
        NIncome2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NIncome2.setForeground(new java.awt.Color(51, 51, 51));
        NIncome2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NIncome2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NIncome2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NIncome2KeyTyped(evt);
            }
        });
        jPanel94.add(NIncome2);

        jLabel199.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel199.setForeground(new java.awt.Color(51, 51, 51));
        jLabel199.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel199.setText("EBIT");
        jPanel94.add(jLabel199);

        EBIT2.setBackground(new java.awt.Color(204, 204, 204));
        EBIT2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        EBIT2.setForeground(new java.awt.Color(51, 51, 51));
        EBIT2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EBIT2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EBIT2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EBIT2KeyTyped(evt);
            }
        });
        jPanel94.add(EBIT2);

        jPanel95.setBackground(new java.awt.Color(0, 153, 255));

        jLabel200.setBackground(new java.awt.Color(0, 153, 255));
        jLabel200.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel200.setForeground(new java.awt.Color(51, 51, 51));
        jLabel200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel200.setText("Cash Flow");

        javax.swing.GroupLayout jPanel95Layout = new javax.swing.GroupLayout(jPanel95);
        jPanel95.setLayout(jPanel95Layout);
        jPanel95Layout.setHorizontalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel200, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        jPanel95Layout.setVerticalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel200, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jPanel94.add(jPanel95);

        jPanel96.setBackground(new java.awt.Color(0, 153, 255));

        jLabel201.setBackground(new java.awt.Color(0, 153, 255));
        jLabel201.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel201.setForeground(new java.awt.Color(51, 51, 51));
        jLabel201.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel201.setText("Statement");

        javax.swing.GroupLayout jPanel96Layout = new javax.swing.GroupLayout(jPanel96);
        jPanel96.setLayout(jPanel96Layout);
        jPanel96Layout.setHorizontalGroup(
            jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel201, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        jPanel96Layout.setVerticalGroup(
            jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel201, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jPanel94.add(jPanel96);

        jLabel202.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel202.setForeground(new java.awt.Color(51, 51, 51));
        jLabel202.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel202.setText("Common Stock Dividend Paid");
        jPanel94.add(jLabel202);

        ComDiv2.setBackground(new java.awt.Color(204, 204, 204));
        ComDiv2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ComDiv2.setForeground(new java.awt.Color(51, 51, 51));
        ComDiv2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ComDiv2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ComDiv2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ComDiv2KeyTyped(evt);
            }
        });
        jPanel94.add(ComDiv2);

        jPanel97.setBackground(new java.awt.Color(0, 153, 255));

        jLabel203.setBackground(new java.awt.Color(0, 153, 255));
        jLabel203.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel203.setForeground(new java.awt.Color(51, 51, 51));
        jLabel203.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel203.setText("EBIT");

        javax.swing.GroupLayout jPanel97Layout = new javax.swing.GroupLayout(jPanel97);
        jPanel97.setLayout(jPanel97Layout);
        jPanel97Layout.setHorizontalGroup(
            jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel203, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        jPanel97Layout.setVerticalGroup(
            jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel203, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jPanel94.add(jPanel97);

        jPanel98.setBackground(new java.awt.Color(0, 153, 255));

        jLabel204.setBackground(new java.awt.Color(0, 153, 255));
        jLabel204.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel204.setForeground(new java.awt.Color(51, 51, 51));
        jLabel204.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel204.setText("Calculation");

        javax.swing.GroupLayout jPanel98Layout = new javax.swing.GroupLayout(jPanel98);
        jPanel98.setLayout(jPanel98Layout);
        jPanel98Layout.setHorizontalGroup(
            jPanel98Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel204, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        jPanel98Layout.setVerticalGroup(
            jPanel98Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel204, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jPanel94.add(jPanel98);

        jLabel205.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel205.setForeground(new java.awt.Color(51, 51, 51));
        jLabel205.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel205.setText("Taxes");
        jPanel94.add(jLabel205);

        Taxes2.setBackground(new java.awt.Color(204, 204, 204));
        Taxes2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Taxes2.setForeground(new java.awt.Color(51, 51, 51));
        Taxes2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Taxes2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Taxes2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Taxes2KeyTyped(evt);
            }
        });
        jPanel94.add(Taxes2);

        jLabel206.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel206.setForeground(new java.awt.Color(51, 51, 51));
        jLabel206.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel206.setText("Interest Expense");
        jPanel94.add(jLabel206);

        IntExp2.setBackground(new java.awt.Color(204, 204, 204));
        IntExp2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        IntExp2.setForeground(new java.awt.Color(51, 51, 51));
        IntExp2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IntExp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IntExp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IntExp2KeyTyped(evt);
            }
        });
        jPanel94.add(IntExp2);

        jPanel93.add(jPanel94);

        jPanel99.setBackground(new java.awt.Color(255, 255, 255));
        jPanel99.setLayout(new java.awt.GridLayout(11, 2));

        jLabel207.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel207.setForeground(new java.awt.Color(51, 51, 51));
        jLabel207.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel207.setText("Total Assets");
        jPanel99.add(jLabel207);

        TAssets2.setBackground(new java.awt.Color(204, 204, 204));
        TAssets2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TAssets2.setForeground(new java.awt.Color(51, 51, 51));
        TAssets2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TAssets2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TAssets2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TAssets2KeyTyped(evt);
            }
        });
        jPanel99.add(TAssets2);

        jLabel208.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel208.setForeground(new java.awt.Color(51, 51, 51));
        jLabel208.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel208.setText("Current Assets");
        jPanel99.add(jLabel208);

        CurAssets2.setBackground(new java.awt.Color(204, 204, 204));
        CurAssets2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CurAssets2.setForeground(new java.awt.Color(51, 51, 51));
        CurAssets2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurAssets2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CurAssets2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CurAssets2KeyTyped(evt);
            }
        });
        jPanel99.add(CurAssets2);

        jLabel209.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel209.setForeground(new java.awt.Color(51, 51, 51));
        jLabel209.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel209.setText("Receivable");
        jPanel99.add(jLabel209);

        Receivable2.setBackground(new java.awt.Color(204, 204, 204));
        Receivable2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Receivable2.setForeground(new java.awt.Color(51, 51, 51));
        Receivable2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Receivable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Receivable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Receivable2KeyTyped(evt);
            }
        });
        jPanel99.add(Receivable2);

        jLabel210.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel210.setForeground(new java.awt.Color(51, 51, 51));
        jLabel210.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel210.setText("Inventory");
        jPanel99.add(jLabel210);

        Inv2.setBackground(new java.awt.Color(204, 204, 204));
        Inv2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Inv2.setForeground(new java.awt.Color(51, 51, 51));
        Inv2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Inv2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Inv2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Inv2KeyTyped(evt);
            }
        });
        jPanel99.add(Inv2);

        jLabel211.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel211.setForeground(new java.awt.Color(51, 51, 51));
        jLabel211.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel211.setText("Total Liabilities Net Minority Interest");
        jPanel99.add(jLabel211);

        TLiabilities2.setBackground(new java.awt.Color(204, 204, 204));
        TLiabilities2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TLiabilities2.setForeground(new java.awt.Color(51, 51, 51));
        TLiabilities2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TLiabilities2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TLiabilities2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TLiabilities2KeyTyped(evt);
            }
        });
        jPanel99.add(TLiabilities2);

        jLabel212.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel212.setForeground(new java.awt.Color(51, 51, 51));
        jLabel212.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel212.setText("Current Liabilities");
        jPanel99.add(jLabel212);

        CurLiabilities2.setBackground(new java.awt.Color(204, 204, 204));
        CurLiabilities2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CurLiabilities2.setForeground(new java.awt.Color(51, 51, 51));
        CurLiabilities2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurLiabilities2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CurLiabilities2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CurLiabilities2KeyTyped(evt);
            }
        });
        jPanel99.add(CurLiabilities2);

        jLabel213.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel213.setForeground(new java.awt.Color(51, 51, 51));
        jLabel213.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel213.setText("Total Equity Gross Minority Interest");
        jPanel99.add(jLabel213);

        TEGMI2.setBackground(new java.awt.Color(204, 204, 204));
        TEGMI2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TEGMI2.setForeground(new java.awt.Color(51, 51, 51));
        TEGMI2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TEGMI2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TEGMI2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TEGMI2KeyTyped(evt);
            }
        });
        jPanel99.add(TEGMI2);

        jLabel214.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel214.setForeground(new java.awt.Color(51, 51, 51));
        jLabel214.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel214.setText("Shareholders Equity");
        jPanel99.add(jLabel214);

        SHEquity2.setBackground(new java.awt.Color(204, 204, 204));
        SHEquity2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        SHEquity2.setForeground(new java.awt.Color(51, 51, 51));
        SHEquity2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SHEquity2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SHEquity2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SHEquity2KeyTyped(evt);
            }
        });
        jPanel99.add(SHEquity2);

        jLabel215.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel215.setForeground(new java.awt.Color(51, 51, 51));
        jLabel215.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel215.setText("Capital Lease Obligations");
        jPanel99.add(jLabel215);

        CapLO2.setBackground(new java.awt.Color(204, 204, 204));
        CapLO2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CapLO2.setForeground(new java.awt.Color(51, 51, 51));
        CapLO2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapLO2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CapLO2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CapLO2KeyTyped(evt);
            }
        });
        jPanel99.add(CapLO2);

        jLabel216.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel216.setForeground(new java.awt.Color(51, 51, 51));
        jLabel216.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel216.setText("Tangible Book Value");
        jPanel99.add(jLabel216);

        TanBookVal2.setBackground(new java.awt.Color(204, 204, 204));
        TanBookVal2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TanBookVal2.setForeground(new java.awt.Color(51, 51, 51));
        TanBookVal2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TanBookVal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TanBookVal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TanBookVal2KeyTyped(evt);
            }
        });
        jPanel99.add(TanBookVal2);

        jLabel217.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel217.setForeground(new java.awt.Color(51, 51, 51));
        jLabel217.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel217.setText("Ordinary Shares Number");
        jPanel99.add(jLabel217);

        OrShNum2.setBackground(new java.awt.Color(204, 204, 204));
        OrShNum2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        OrShNum2.setForeground(new java.awt.Color(51, 51, 51));
        OrShNum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        OrShNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        OrShNum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OrShNum2KeyTyped(evt);
            }
        });
        jPanel99.add(OrShNum2);

        jPanel93.add(jPanel99);

        RatioIn.add(jPanel93, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1198, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(RatioIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RatioIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TRevenue2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TRevenue2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_TRevenue2KeyTyped

    private void CofRevenue2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CofRevenue2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_CofRevenue2KeyTyped

    private void OpExpense2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OpExpense2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_OpExpense2KeyTyped

    private void OthIncome2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OthIncome2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_OthIncome2KeyTyped

    private void NIncome2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIncome2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_NIncome2KeyTyped

    private void EBIT2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EBIT2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_EBIT2KeyTyped

    private void ComDiv2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComDiv2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_ComDiv2KeyTyped

    private void Taxes2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Taxes2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_Taxes2KeyTyped

    private void IntExp2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IntExp2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_IntExp2KeyTyped

    private void TAssets2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TAssets2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_TAssets2KeyTyped

    private void CurAssets2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CurAssets2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_CurAssets2KeyTyped

    private void Receivable2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Receivable2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_Receivable2KeyTyped

    private void Inv2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Inv2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_Inv2KeyTyped

    private void TLiabilities2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TLiabilities2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_TLiabilities2KeyTyped

    private void CurLiabilities2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CurLiabilities2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_CurLiabilities2KeyTyped

    private void TEGMI2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TEGMI2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_TEGMI2KeyTyped

    private void SHEquity2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SHEquity2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_SHEquity2KeyTyped

    private void CapLO2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CapLO2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_CapLO2KeyTyped

    private void TanBookVal2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TanBookVal2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_TanBookVal2KeyTyped

    private void OrShNum2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OrShNum2KeyTyped
        controller.keyCheck(evt);
    }//GEN-LAST:event_OrShNum2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CapLO2;
    private javax.swing.JTextField CofRevenue2;
    private javax.swing.JTextField ComDiv2;
    private javax.swing.JTextField CurAssets2;
    private javax.swing.JTextField CurLiabilities2;
    private javax.swing.JTextField EBIT2;
    private javax.swing.JTextField IntExp2;
    private javax.swing.JTextField Inv2;
    private javax.swing.JTextField NIncome2;
    private javax.swing.JTextField OpExpense2;
    private javax.swing.JTextField OrShNum2;
    private javax.swing.JTextField OthIncome2;
    private javax.swing.JPanel RatioIn;
    private javax.swing.JTextField Receivable2;
    private javax.swing.JTextField SHEquity2;
    private javax.swing.JTextField TAssets2;
    private javax.swing.JTextField TEGMI2;
    private javax.swing.JTextField TLiabilities2;
    private javax.swing.JTextField TRevenue2;
    private javax.swing.JTextField TanBookVal2;
    private javax.swing.JTextField Taxes2;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel216;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JPanel jPanel92;
    private javax.swing.JPanel jPanel93;
    private javax.swing.JPanel jPanel94;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JPanel jPanel96;
    private javax.swing.JPanel jPanel97;
    private javax.swing.JPanel jPanel98;
    private javax.swing.JPanel jPanel99;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return
     */
    public JTextField getCapLO() {
        return CapLO2;
    }

    /**
     *
     * @return
     */
    public JTextField getCofRevenue() {
        return CofRevenue2;
    }

    /**
     *
     * @return
     */
    public JTextField getComDiv() {
        return ComDiv2;
    }

    /**
     *
     * @return
     */
    public JTextField getCurAssets() {
        return CurAssets2;
    }

    /**
     *
     * @return
     */
    public JTextField getCurLiabilities() {
        return CurLiabilities2;
    }

    /**
     *
     * @return
     */
    public JTextField getEBIT() {
        return EBIT2;
    }

    /**
     *
     * @return
     */
    public JTextField getIntExp() {
        return IntExp2;
    }

    /**
     *
     * @return
     */
    public JTextField getInv() {
        return Inv2;
    }

    /**
     *
     * @return
     */
    public JTextField getNIncome() {
        return NIncome2;
    }

    /**
     *
     * @return
     */
    public JTextField getOpExpense() {
        return OpExpense2;
    }

    /**
     *
     * @return
     */
    public JTextField getOrShNum() {
        return OrShNum2;
    }

    /**
     *
     * @return
     */
    public JTextField getOthIncome() {
        return OthIncome2;
    }

    /**
     *
     * @return
     */
    public JPanel getRatioIn() {
        return RatioIn;
    }

    /**
     *
     * @return
     */
    public JTextField getReceivable() {
        return Receivable2;
    }

    /**
     *
     * @return
     */
    public JTextField getSHEquity() {
        return SHEquity2;
    }

    /**
     *
     * @return
     */
    public JTextField getTAssets() {
        return TAssets2;
    }

    /**
     *
     * @return
     */
    public JTextField getTEGMI() {
        return TEGMI2;
    }

    /**
     *
     * @return
     */
    public JTextField getTLiabilities() {
        return TLiabilities2;
    }

    /**
     *
     * @return
     */
    public JTextField getTRevenue() {
        return TRevenue2;
    }

    /**
     *
     * @return
     */
    public JTextField getTanBookVal() {
        return TanBookVal2;
    }

    /**
     *
     * @return
     */
    public JTextField getTaxes() {
        return Taxes2;
    }

}
