/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ondre
 */
public class SummaryOutput extends javax.swing.JPanel {

    /**
     * Creates new form SummaryOutput
     */
    public SummaryOutput() {
        initComponents();
    }

    public void setLabels(String fileRoute) {
        Properties p = new Properties();
        FileInputStream ip;
        try {
            ip = new FileInputStream(fileRoute);
            p.load(ip);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RatioInput.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GrahamOutput.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel67.setText(p.getProperty("jLabel67"));
        jLabel72.setText(p.getProperty("DCF"));
        jLabel73.setText(p.getProperty("DDM"));
        jLabel74.setText(p.getProperty("Graham"));
        jLabel88.setText(p.getProperty("jLabel88"));
        jLabel75.setText(p.getProperty("NAV"));
        jLabel76.setText(p.getProperty("price"));
        jLabel77.setText(p.getProperty("price"));
        jLabel78.setText(p.getProperty("price"));
        jLabel79.setText(p.getProperty("price"));
        jLabel80.setText(p.getProperty("price"));
        jLabel81.setText(p.getProperty("pricemos"));
        jLabel82.setText(p.getProperty("pricemos"));
        jLabel83.setText(p.getProperty("pricemos"));
        jLabel84.setText(p.getProperty("pricemos"));
        jLabel85.setText(p.getProperty("pricemos"));
        jLabel68.setText(p.getProperty("jLabel68"));
        jLabel70.setText(p.getProperty("jLabel70"));
        jLabel69.setText(p.getProperty("jLabel69"));
        jLabel71.setText(p.getProperty("mos"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SummaryOut = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        SumSticker = new javax.swing.JTextField();
        ActPriceAns = new javax.swing.JTextField();
        jPanel34 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        IdealPrice = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        IdealPriceMoS = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        Diff = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        PillowAns = new javax.swing.JTextField();
        jPanel35 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        DCFAns = new javax.swing.JTextField();
        jPanel37 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        DDMAns = new javax.swing.JTextField();
        jPanel38 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        GrahamAns = new javax.swing.JTextField();
        jPanel39 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        GrahamRevAns = new javax.swing.JTextField();
        jPanel40 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        NAVAns = new javax.swing.JTextField();
        jPanel41 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        DCFMoSAns = new javax.swing.JTextField();
        jPanel42 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        DDMMoSAns = new javax.swing.JTextField();
        jPanel43 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        GrahamMoSAns = new javax.swing.JTextField();
        jPanel44 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        GrahamRevMoSAns = new javax.swing.JTextField();
        jPanel45 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        NAVMoSAns = new javax.swing.JTextField();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();

        SummaryOut.setLayout(new java.awt.BorderLayout());

        jPanel31.setBackground(new java.awt.Color(0, 153, 255));

        jLabel67.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(51, 51, 51));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Summary valuation of stock");

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        SummaryOut.add(jPanel31, java.awt.BorderLayout.PAGE_START);

        jPanel32.setLayout(new java.awt.BorderLayout());

        jPanel33.setBackground(new java.awt.Color(0, 51, 255));
        jPanel33.setLayout(new java.awt.GridLayout(1, 2));

        SumSticker.setEditable(false);
        SumSticker.setBackground(new java.awt.Color(0, 51, 255));
        SumSticker.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        SumSticker.setForeground(new java.awt.Color(255, 255, 255));
        SumSticker.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SumSticker.setText("Sticker");
        jPanel33.add(SumSticker);

        ActPriceAns.setEditable(false);
        ActPriceAns.setBackground(new java.awt.Color(0, 51, 255));
        ActPriceAns.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ActPriceAns.setForeground(new java.awt.Color(255, 255, 255));
        ActPriceAns.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActPriceAns.setText("Actual Stock Price");
        jPanel33.add(ActPriceAns);

        jPanel32.add(jPanel33, java.awt.BorderLayout.PAGE_START);

        jPanel34.setBackground(new java.awt.Color(102, 255, 255));
        jPanel34.setLayout(new java.awt.GridLayout(2, 4));

        jLabel68.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(51, 51, 51));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Average price:");
        jPanel34.add(jLabel68);

        IdealPrice.setEditable(false);
        IdealPrice.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        IdealPrice.setForeground(new java.awt.Color(204, 204, 204));
        jPanel34.add(IdealPrice);

        jLabel70.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(51, 51, 51));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Averige price with margin:");
        jPanel34.add(jLabel70);

        IdealPriceMoS.setEditable(false);
        IdealPriceMoS.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        IdealPriceMoS.setForeground(new java.awt.Color(204, 204, 204));
        jPanel34.add(IdealPriceMoS);

        jLabel69.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(51, 51, 51));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("Difference:");
        jPanel34.add(jLabel69);

        Diff.setEditable(false);
        Diff.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Diff.setForeground(new java.awt.Color(204, 204, 204));
        jPanel34.add(Diff);

        jLabel71.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(51, 51, 51));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("Margin of Safety:");
        jPanel34.add(jLabel71);

        PillowAns.setEditable(false);
        PillowAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        PillowAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel34.add(PillowAns);

        jPanel32.add(jPanel34, java.awt.BorderLayout.PAGE_END);

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setLayout(new java.awt.GridLayout(4, 5));

        jLabel72.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 102, 255));
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("DCF");
        jPanel35.add(jLabel72);

        jLabel73.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 102, 255));
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("DDM");
        jPanel35.add(jLabel73);

        jLabel74.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 102, 255));
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("Grahams Formulas");
        jPanel35.add(jLabel74);

        jLabel88.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(0, 102, 255));
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel88.setText("Grahams Revs Formula");
        jPanel35.add(jLabel88);

        jLabel75.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(0, 102, 255));
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("NAV");
        jPanel35.add(jLabel75);

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setLayout(new java.awt.GridLayout());

        jLabel76.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(51, 51, 51));
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel76.setText("Price:");
        jPanel36.add(jLabel76);

        DCFAns.setEditable(false);
        DCFAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        DCFAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel36.add(DCFAns);

        jPanel35.add(jPanel36);

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setLayout(new java.awt.GridLayout(1, 2));

        jLabel77.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(51, 51, 51));
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel77.setText("Price:");
        jPanel37.add(jLabel77);

        DDMAns.setEditable(false);
        DDMAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        DDMAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel37.add(DDMAns);

        jPanel35.add(jPanel37);

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setLayout(new java.awt.GridLayout());

        jLabel78.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(51, 51, 51));
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel78.setText("Price:");
        jPanel38.add(jLabel78);

        GrahamAns.setEditable(false);
        GrahamAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GrahamAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel38.add(GrahamAns);

        jPanel35.add(jPanel38);

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setLayout(new java.awt.GridLayout());

        jLabel79.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(51, 51, 51));
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel79.setText("Price:");
        jPanel39.add(jLabel79);

        GrahamRevAns.setEditable(false);
        GrahamRevAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GrahamRevAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel39.add(GrahamRevAns);

        jPanel35.add(jPanel39);

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel40.setLayout(new java.awt.GridLayout());

        jLabel80.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(51, 51, 51));
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel80.setText("Price:");
        jPanel40.add(jLabel80);

        NAVAns.setEditable(false);
        NAVAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NAVAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel40.add(NAVAns);

        jPanel35.add(jPanel40);

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setLayout(new java.awt.GridLayout());

        jLabel81.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(51, 51, 51));
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel81.setText("Price with MoS:");
        jPanel41.add(jLabel81);

        DCFMoSAns.setEditable(false);
        DCFMoSAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        DCFMoSAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel41.add(DCFMoSAns);

        jPanel35.add(jPanel41);

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setLayout(new java.awt.GridLayout());

        jLabel82.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(51, 51, 51));
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel82.setText("Price with MoS:");
        jPanel42.add(jLabel82);

        DDMMoSAns.setEditable(false);
        DDMMoSAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        DDMMoSAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel42.add(DDMMoSAns);

        jPanel35.add(jPanel42);

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel43.setLayout(new java.awt.GridLayout());

        jLabel83.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(51, 51, 51));
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel83.setText("Price with MoS:");
        jPanel43.add(jLabel83);

        GrahamMoSAns.setEditable(false);
        GrahamMoSAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GrahamMoSAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel43.add(GrahamMoSAns);

        jPanel35.add(jPanel43);

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel44.setLayout(new java.awt.GridLayout());

        jLabel84.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(51, 51, 51));
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel84.setText("Price with MoS:");
        jPanel44.add(jLabel84);

        GrahamRevMoSAns.setEditable(false);
        GrahamRevMoSAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GrahamRevMoSAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel44.add(GrahamRevMoSAns);

        jPanel35.add(jPanel44);

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setLayout(new java.awt.GridLayout());

        jLabel85.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(51, 51, 51));
        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel85.setText("Price with MoS:");
        jPanel45.add(jLabel85);

        NAVMoSAns.setEditable(false);
        NAVMoSAns.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NAVMoSAns.setForeground(new java.awt.Color(204, 204, 204));
        jPanel45.add(NAVMoSAns);

        jPanel35.add(jPanel45);

        jPanel46.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel46);

        jPanel47.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel47);

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel48);

        jPanel49.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel49);

        jPanel50.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel50);

        jPanel32.add(jPanel35, java.awt.BorderLayout.CENTER);

        SummaryOut.add(jPanel32, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(SummaryOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(SummaryOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActPriceAns;
    private javax.swing.JTextField DCFAns;
    private javax.swing.JTextField DCFMoSAns;
    private javax.swing.JTextField DDMAns;
    private javax.swing.JTextField DDMMoSAns;
    private javax.swing.JTextField Diff;
    private javax.swing.JTextField GrahamAns;
    private javax.swing.JTextField GrahamMoSAns;
    private javax.swing.JTextField GrahamRevAns;
    private javax.swing.JTextField GrahamRevMoSAns;
    private javax.swing.JTextField IdealPrice;
    private javax.swing.JTextField IdealPriceMoS;
    private javax.swing.JTextField NAVAns;
    private javax.swing.JTextField NAVMoSAns;
    private javax.swing.JTextField PillowAns;
    private javax.swing.JTextField SumSticker;
    private javax.swing.JPanel SummaryOut;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    // End of variables declaration//GEN-END:variables

    public JTextField getActPriceAns() {
        return ActPriceAns;
    }

    public JTextField getDCFAns() {
        return DCFAns;
    }

    public JTextField getDCFMoSAns() {
        return DCFMoSAns;
    }

    public JTextField getDDMAns() {
        return DDMAns;
    }

    public JTextField getDDMMoSAns() {
        return DDMMoSAns;
    }

    public JTextField getDiff() {
        return Diff;
    }

    public JTextField getGrahamAns() {
        return GrahamAns;
    }

    public JTextField getGrahamMoSAns() {
        return GrahamMoSAns;
    }

    public JTextField getGrahamRevAns() {
        return GrahamRevAns;
    }

    public JTextField getGrahamRevMoSAns() {
        return GrahamRevMoSAns;
    }

    public JTextField getIdealPrice() {
        return IdealPrice;
    }

    public JTextField getIdealPriceMoS() {
        return IdealPriceMoS;
    }

    public JTextField getNAVAns() {
        return NAVAns;
    }

    public JTextField getNAVMoSAns() {
        return NAVMoSAns;
    }

    public JTextField getPillowAns() {
        return PillowAns;
    }

    public JTextField getSumSticker() {
        return SumSticker;
    }

    public JPanel getSummaryOut() {
        return SummaryOut;
    }

}
