/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Valuator;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ondre
 * 
 * Colors set up:
 * rgb(0, 255, 246)
 * rgb(0, 231, 255)
 * rgb(0, 158, 255)
 * rgb(0, 20, 255)
 * 
 */
public class ReworkedFrontend extends javax.swing.JFrame {

    /**
     * Creates new form ReworkedFrontend
     */
    
    private final Color lightDarkColor;
    private final Color darkLightColor;
    
    public ReworkedFrontend() {
        lightDarkColor = new Color(0, 231, 255);
        darkLightColor = new Color(0, 20, 255);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calculation = new javax.swing.JPanel();
        UseDCF = new javax.swing.JCheckBox();
        UseRatios = new javax.swing.JCheckBox();
        BorderOne = new javax.swing.JPanel();
        UseDDM = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        UseGraham = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        BorderTwo = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        MenuColumn = new javax.swing.JPanel();
        ShowHideBut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CorpChoice = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CorpDivChoice = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BankChoice = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NonProfitChoice = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        HidingMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        Calculation.setBackground(new java.awt.Color(0, 20, 255));
        Calculation.setForeground(new java.awt.Color(0, 102, 255));
        Calculation.setLayout(new java.awt.GridLayout(3, 4));

        UseDCF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UseDCF.setForeground(new java.awt.Color(255, 255, 255));
        UseDCF.setText("DCF");
        UseDCF.setToolTipText("Enable / Disable Discounted Cash Flow Model");
        Calculation.add(UseDCF);

        UseRatios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UseRatios.setForeground(new java.awt.Color(255, 255, 255));
        UseRatios.setText("Ratios");
        UseRatios.setToolTipText("Enable / Disable Ratios");
        Calculation.add(UseRatios);

        BorderOne.setBackground(new java.awt.Color(0, 20, 255));

        javax.swing.GroupLayout BorderOneLayout = new javax.swing.GroupLayout(BorderOne);
        BorderOne.setLayout(BorderOneLayout);
        BorderOneLayout.setHorizontalGroup(
            BorderOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        BorderOneLayout.setVerticalGroup(
            BorderOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        Calculation.add(BorderOne);

        UseDDM.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UseDDM.setForeground(new java.awt.Color(255, 255, 255));
        UseDDM.setText("DDM");
        UseDDM.setToolTipText("Enable / Disable Dividend Discount Model");
        Calculation.add(UseDDM);

        jCheckBox5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Feature 1");
        Calculation.add(jCheckBox5);

        UseGraham.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UseGraham.setForeground(new java.awt.Color(255, 255, 255));
        UseGraham.setText("Grahams formulas");
        UseGraham.setToolTipText("Enable / Disable Grahams formulas");
        Calculation.add(UseGraham);

        jCheckBox6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Feature 2");
        Calculation.add(jCheckBox6);

        BorderTwo.setBackground(new java.awt.Color(0, 20, 255));

        javax.swing.GroupLayout BorderTwoLayout = new javax.swing.GroupLayout(BorderTwo);
        BorderTwo.setLayout(BorderTwoLayout);
        BorderTwoLayout.setHorizontalGroup(
            BorderTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        BorderTwoLayout.setVerticalGroup(
            BorderTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        Calculation.add(BorderTwo);

        getContentPane().add(Calculation, java.awt.BorderLayout.PAGE_END);

        Menu.setBackground(new java.awt.Color(102, 204, 255));
        Menu.setLayout(new java.awt.BorderLayout());

        MenuColumn.setBackground(new java.awt.Color(0, 255, 246));
        MenuColumn.setLayout(new java.awt.GridLayout(6, 1));

        ShowHideBut.setBackground(new java.awt.Color(0, 255, 246));
        ShowHideBut.setPreferredSize(new java.awt.Dimension(50, 50));
        ShowHideBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowHideButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShowHideButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ShowHideButMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu-edit.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout ShowHideButLayout = new javax.swing.GroupLayout(ShowHideBut);
        ShowHideBut.setLayout(ShowHideButLayout);
        ShowHideButLayout.setHorizontalGroup(
            ShowHideButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        ShowHideButLayout.setVerticalGroup(
            ShowHideButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MenuColumn.add(ShowHideBut);

        CorpChoice.setBackground(new java.awt.Color(0, 255, 246));
        CorpChoice.setPreferredSize(new java.awt.Dimension(50, 50));
        CorpChoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CorpChoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CorpChoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CorpChoiceMouseExited(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/corp-edit.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CorpChoiceLayout = new javax.swing.GroupLayout(CorpChoice);
        CorpChoice.setLayout(CorpChoiceLayout);
        CorpChoiceLayout.setHorizontalGroup(
            CorpChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        CorpChoiceLayout.setVerticalGroup(
            CorpChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MenuColumn.add(CorpChoice);

        CorpDivChoice.setBackground(new java.awt.Color(0, 255, 246));
        CorpDivChoice.setPreferredSize(new java.awt.Dimension(50, 50));
        CorpDivChoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CorpDivChoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CorpDivChoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CorpDivChoiceMouseExited(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dividends-edit.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CorpDivChoiceLayout = new javax.swing.GroupLayout(CorpDivChoice);
        CorpDivChoice.setLayout(CorpDivChoiceLayout);
        CorpDivChoiceLayout.setHorizontalGroup(
            CorpDivChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        CorpDivChoiceLayout.setVerticalGroup(
            CorpDivChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MenuColumn.add(CorpDivChoice);

        BankChoice.setBackground(new java.awt.Color(0, 255, 246));
        BankChoice.setPreferredSize(new java.awt.Dimension(50, 50));
        BankChoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BankChoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BankChoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BankChoiceMouseExited(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bank-edit.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout BankChoiceLayout = new javax.swing.GroupLayout(BankChoice);
        BankChoice.setLayout(BankChoiceLayout);
        BankChoiceLayout.setHorizontalGroup(
            BankChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        BankChoiceLayout.setVerticalGroup(
            BankChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MenuColumn.add(BankChoice);

        NonProfitChoice.setBackground(new java.awt.Color(0, 255, 246));
        NonProfitChoice.setPreferredSize(new java.awt.Dimension(50, 50));
        NonProfitChoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NonProfitChoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NonProfitChoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NonProfitChoiceMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/solidarity-edit.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout NonProfitChoiceLayout = new javax.swing.GroupLayout(NonProfitChoice);
        NonProfitChoice.setLayout(NonProfitChoiceLayout);
        NonProfitChoiceLayout.setHorizontalGroup(
            NonProfitChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        NonProfitChoiceLayout.setVerticalGroup(
            NonProfitChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MenuColumn.add(NonProfitChoice);

        Menu.add(MenuColumn, java.awt.BorderLayout.LINE_START);

        HidingMenu.setBackground(new java.awt.Color(0, 231, 255));
        HidingMenu.setLayout(new java.awt.GridLayout(5, 1));
        Menu.add(HidingMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changeColor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    private void ShowHideButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowHideButMouseEntered
        changeColor(ShowHideBut, lightDarkColor);
    }//GEN-LAST:event_ShowHideButMouseEntered

    private void ShowHideButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowHideButMouseExited
        changeColor(ShowHideBut, new Color(0, 255, 246));
    }//GEN-LAST:event_ShowHideButMouseExited

    private void ShowHideButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowHideButMouseClicked
        changeColor(ShowHideBut, lightDarkColor);
    }//GEN-LAST:event_ShowHideButMouseClicked

    private void CorpChoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorpChoiceMouseEntered
        changeColor(CorpChoice, lightDarkColor);
    }//GEN-LAST:event_CorpChoiceMouseEntered

    private void CorpChoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorpChoiceMouseExited
        changeColor(CorpChoice, new Color(0, 255, 246));
    }//GEN-LAST:event_CorpChoiceMouseExited

    private void CorpChoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorpChoiceMouseClicked
        changeColor(CorpChoice, lightDarkColor);
    }//GEN-LAST:event_CorpChoiceMouseClicked

    private void CorpDivChoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorpDivChoiceMouseEntered
        changeColor(CorpDivChoice, lightDarkColor);
    }//GEN-LAST:event_CorpDivChoiceMouseEntered

    private void CorpDivChoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorpDivChoiceMouseExited
        changeColor(CorpDivChoice, new Color(0, 255, 246));
    }//GEN-LAST:event_CorpDivChoiceMouseExited

    private void CorpDivChoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorpDivChoiceMouseClicked
        changeColor(CorpDivChoice, lightDarkColor);
    }//GEN-LAST:event_CorpDivChoiceMouseClicked

    private void BankChoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BankChoiceMouseEntered
        changeColor(BankChoice, lightDarkColor);
    }//GEN-LAST:event_BankChoiceMouseEntered

    private void BankChoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BankChoiceMouseExited
        changeColor(BankChoice, new Color(0, 255, 246));
    }//GEN-LAST:event_BankChoiceMouseExited

    private void BankChoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BankChoiceMouseClicked
        changeColor(BankChoice, lightDarkColor);
    }//GEN-LAST:event_BankChoiceMouseClicked

    private void NonProfitChoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NonProfitChoiceMouseEntered
        changeColor(NonProfitChoice, lightDarkColor);
    }//GEN-LAST:event_NonProfitChoiceMouseEntered

    private void NonProfitChoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NonProfitChoiceMouseExited
        changeColor(NonProfitChoice, new Color(0, 255, 246));
    }//GEN-LAST:event_NonProfitChoiceMouseExited

    private void NonProfitChoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NonProfitChoiceMouseClicked
        changeColor(NonProfitChoice, lightDarkColor);
    }//GEN-LAST:event_NonProfitChoiceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //řeší problém se škálováním ikon
        System.setProperty("sun.java2d.uiScale", "1");
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReworkedFrontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReworkedFrontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReworkedFrontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReworkedFrontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReworkedFrontend().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BankChoice;
    private javax.swing.JPanel BorderOne;
    private javax.swing.JPanel BorderTwo;
    private javax.swing.JPanel Calculation;
    private javax.swing.JPanel CorpChoice;
    private javax.swing.JPanel CorpDivChoice;
    private javax.swing.JPanel HidingMenu;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuColumn;
    private javax.swing.JPanel NonProfitChoice;
    private javax.swing.JPanel ShowHideBut;
    private javax.swing.JCheckBox UseDCF;
    private javax.swing.JCheckBox UseDDM;
    private javax.swing.JCheckBox UseGraham;
    private javax.swing.JCheckBox UseRatios;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
